### ISSUE TITLE
[AX92U][388.1]Connection down after a few days

### ISSUE THREAD

**Issue by nnciprian** [gnuton/asuswrt-merlin.ng#358] opened 2023-03-22 06:41 UTC
**Router Model Affected**
Models: RT-AX92U

**Firmware Version Affected**
388.1

**Is this bug present in upstream Merlin releases too?**
N/A

> llegodmin@RT-AX92U-6690:/tmp/etc/email# free -h
>              total       used       free     shared    buffers     cached
> Mem:        380188     351044      29144       4012          0      39500
> -/+ buffers/cache:     311544      68644
> Swap:            0          0          0

Also there seems to be enough space

> user@RT-AX92U-6690:/tmp/etc/email# df -h
> Filesystem                Size      Used Available Use% Mounted on
> ubi:rootfs_ubifs         69.4M     65.6M      3.9M  94% /
> devtmpfs                185.5M         0    185.5M   0% /dev
> tmpfs                   185.6M    280.0K    185.4M   0% /var
> tmpfs                   185.6M      3.5M    182.1M   2% /tmp/mnt
> mtd:bootfs                5.1M      4.2M    980.0K  81% /bootfs
> mtd:data                  8.0M    604.0K      7.4M   7% /data
> tmpfs                   185.6M      3.5M    182.1M   2% /tmp/mnt
> tmpfs                   185.6M      3.5M    182.1M   2% /tmp
> /dev/mtdblock9           63.0M      6.4M     56.6M  10% /jffs

After a few days of uptime, in this case 5 days router is disconnected from the internet and I have to reboot to connect again. Internet LED does not go red (i.e. stays white).
In system log I see some memory outages sometimes and no free space left on the device on some mounts;.
I attached system log for today's event since 00:00AM. Link down I believe it happened around 5 am;

[syslog_git.txt](https://github.com/gnuton/asuswrt-merlin.ng/files/11037142/syslog_git.txt)
Some screenshots attached;
<img width="224" alt="ax92u" src="https://user-images.githubusercontent.com/12816820/226822480-3c9bb397-9767-43a4-afc7-4378c30dc098.png">
<img width="572" alt="ax92u_1" src="https://user-images.githubusercontent.com/12816820/226822483-fbba7739-159b-4360-9e13-17b62cc4feed.png">

Later edit: Reading https://github.com/gnuton/asuswrt-merlin.ng/issues/334 i stopped connection diagnostics, monitoring now

**Comment by nnciprian** [comment] 2023-06-15 08:52
after connection diagnostics issue still persists

Jun 14 16:23:51 dnsmasq-dhcp[16036]: failed to write /var/lib/misc/dnsmasq.leases: No space left on device (retry in 60 s)

**Comment by gnuton** [comment] 2023-06-15 09:15
Please update to latest stable

**Comment by gnuton** [comment] 2023-06-15 09:16
duplicate of  #334

**Closed by gnuton** 2023-06-15 09:16 UTC
Labels: bug

**Comment by nnciprian** [comment] 2023-06-17 16:24
updated to 388.2_2_0 ;
Monitoring
