### ISSUE TITLE
[388.2.2-beta2] Cannot flash firmware to AIMesh nodes

### ISSUE THREAD

**Issue by gshpychka** [gnuton/asuswrt-merlin.ng#401] opened 2023-05-28 17:59 UTC
**Router Model Affected**
RT-AXE95Q ZenWifi ET8

**Firmware Version Affected**
388.2_2-gnuton0_beta2

**Is this bug present in upstream Merlin releases too?**
Unknown

**Describe the bug**
Not able to update the firmware of AIMesh nodes

**To Reproduce**
1. Set up AIMesh nodes. 
2. Go to /Advanced_FirmwareUpgrade_Content.asp
3. Only the main router is listed - nodes do not appear.

**Expected behavior**
Able to flash the firmware of AIMesh nodes. This is working in 388.1.0
**Screenshots**
<img width="761" alt="image" src="https://github.com/gnuton/asuswrt-merlin.ng/assets/23005347/251e0d73-a813-41ca-99f8-9bc9957f8d77">

**Comment by gnuton** [comment] 2023-05-29 22:39
duplicate of https://github.com/gnuton/asuswrt-merlin.ng/issues/374

**Closed by gnuton** 2023-05-29 22:39 UTC
Labels: bug, alpha, beta, 388_2, et8
