### ISSUE TITLE
Stability Adjustment section and negative numbers

### ISSUE THREAD

**Issue by Hello-olleH** [gnuton/asuswrt-merlin.ng#110] opened 2021-07-03 21:13 UTC
**Firmware Version Affected **
386.02_6-gnuton1

**Describe the bug**
In the original firmware, there are also negative numbers in the Stability Adjustment section, and by selecting these numbers, my internet speed will increase. For example, by selecting the -5, my speed will reach 87294 kbps. There are no negative numbers inside the Merlin firmware and my speed does not exceed 70871 Kbps.

**Screenshots**
<img width="1517" alt="Screenshot 2021-06-25 at 13 21 17" src="https://user-images.githubusercontent.com/45637723/124366977-f4a85180-dc53-11eb-97e8-d607544d70f1.png">
<img width="1479" alt="Screenshot 2021-06-25 at 13 24 03" src="https://user-images.githubusercontent.com/45637723/124366979-f70aab80-dc53-11eb-858f-009d6d6ac81c.png">
<img width="1465" alt="Screenshot 2021-06-25 at 13 24 38" src="https://user-images.githubusercontent.com/45637723/124366981-f83bd880-dc53-11eb-90c7-8b89c35603e0.png">
<img width="1498" alt="Screenshot 2021-06-25 at 13 18 25" src="https://user-images.githubusercontent.com/45637723/124366983-fa059c00-dc53-11eb-8084-e100dcc0ca52.png">
<img width="1512" alt="Screen Shot 2021-07-03 at 23 12 26" src="https://user-images.githubusercontent.com/45637723/124367014-3507cf80-dc54-11eb-9edd-b0ca674df5ba.png">

**Comment by gnuton** [comment] 2021-07-10 06:21
Hi,
This is the new UI which comes with 43xxx GPLs and Merlin is still using 42095.
So it will be updated when we do switch to the new one.

**Comment by Katana1074** [comment] 2021-11-22 22:11
Hi I can confirm that this is fixed in Version 3.0.0.4.386.45660 of the original ASUS firmware, we will just have to be patient and wait for ASUS to release the GPL for 3.0.0.4.386.45660....

Regards

Katana1074

**Comment by gnuton** [comment] 2022-01-05 18:59
This has been fixed. The fix is in the master branch and it will be available along with the next release.

**Comment by gnuton** [comment] 2022-01-05 19:00
this was a duplicate of this issue: https://github.com/gnuton/asuswrt-merlin.ng/issues/136

**Closed by gnuton** 2022-01-05 18:59 UTC
Labels: enhancement, WaitingForFixFromASUS
