### ISSUE TITLE
WAN - Virtual Server / Port Forwarding

### ISSUE THREAD

**Issue by zendilar** [gnuton/asuswrt-merlin.ng#18] opened 2019-05-15 17:42 UTC
If you go to http://router.asus.com/Advanced_VirtualServer_Content.asp and Enable Port Forwarding and add some rules in the list, the router does not save them, after a reboot the list is empty and you have to add them again.

please take a look if that can be fixed

I am running DSL-AC68U_384.11_gnutonalpha2_DSL_1.0.4.7.trx
thanks again for the FW

**Comment by juwgxibz** [comment] 2019-05-15 17:56
It's working, but not stable.
In RMerlin's firmware the same situation, I've wrote about this bug in SMB.

**Comment by zendilar** [comment] 2019-05-15 18:19
at my home router I am running DSL-AC68U_384.10_gnuton4_DSL_1.0.4.7.trx and there is no issue with Port Forwarding rules in the list

**Comment by gnuton** [comment] 2019-05-15 19:17
Followed the steps you said  and it worked for me on 384.11_gnutonalpha2.
@zendilar please reset to factory and try again if that happens please tell me what you do to let it fail.
@juwgxibz what do you mean with it's unstable? is this issue reported in the RMerl github?

**Comment by Keltere** [comment] 2019-05-15 20:58
Tested with 384.11_gnutonalpha2 and no problem.
I use DSL connection.
@zendilar how many ports did you set? Or even better, can you give us the list?

**Comment by juwgxibz** [comment] 2019-05-16 05:12
I mean somtimes rules saved somtimes not. I don't know why.
Not reported RMerlin gintub yet, just asked question in SBM forum.

**Comment by gnuton** [comment] 2019-05-16 20:05
I will close this since I do not see an issue here. If you keep on having this prolbem we will re-open it.
cheers

**Closed by gnuton** 2019-05-16 20:05 UTC
Labels: bug

**Comment by jtitley** [comment] 2020-01-19 11:23
I've had this issue with stock firmware, but it is fixed with Merlin, probably because I did a factory reset. The issue is NVRAM is full and for whatever reason, port forwarding is the first to have problems in this scenario. You can do things like clear nvram setting client_info_tmp or a factory reset (because things like multiple VPN servers can add entries in nvram and don't go away unless you clear).

My workaround was to update NAT in one of the startup scripts. Since I didn't change port forwarding often, it was fine for me to update via command line. Just nvram get vts_rulelist and then call nvram set vts_rulelist on boot.

Because I implemented this on stock, I used the post-mount hack to run this at that time.
