### ISSUE TITLE
TUF AX3000 BUGS

### ISSUE THREAD

**Issue by ikunfans** [gnuton/asuswrt-merlin.ng#319] opened 2023-01-08 13:47 UTC
**Router Model Affected**
Models: TUF AX3000

**Firmware Version AffecteDd**
388.1 BETA3

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
rog pc software "gamefrist vi" cant find the support asus routers, i used it to open gamemode on  386 fireware successful.......
and app "instant guard" also cant find support asus router to set up vpn。
page “system log - connections” is still tuf-them

**To Reproduce**

**Comment by gnuton** [comment] 2023-01-15 23:17
Duplicate of https://github.com/gnuton/asuswrt-merlin.ng/issues/323

**Closed by gnuton** 2023-01-15 23:17 UTC
Labels: bug
