### ISSUE TITLE
Administration - Firmware Upgrade Bad Link

### ISSUE THREAD

**Issue by phostetl** [gnuton/asuswrt-merlin.ng#424] opened 2023-06-24 15:10 UTC
**Router Model Affected**
RT-AXE95Q

**Firmware Version Affected**
388.2_2_0-gnuton1

**Is this bug present in upstream Merlin releases too?**
N/A

**Describe the bug**
The link in note #4 on the web interface goes to https://www.asuswrt-merlin.net/download instead of gnuton's stable builds on github.

**To Reproduce**
1. Click the link and get Merlin update site, not Gnuton's site.
4. See the error

**Expected behavior**
The link should take you to gnuton stable releases.

**Screenshots**

**Comment by gnuton** [comment] 2023-06-28 07:38
Thanks for reporting I will check this.

**Comment by gnuton** [comment] 2023-10-04 19:36
This should be fixed in the latest beta

**Comment by gnuton** [comment] 2023-10-04 19:37
duplicate of https://github.com/gnuton/asuswrt-merlin.ng/issues/467

**Closed by gnuton** 2023-10-04 19:37 UTC
Labels: bug
