### ISSUE TITLE
Question regarding 388.2

### ISSUE THREAD

**Issue by hyprsnpr** [gnuton/asuswrt-merlin.ng#360] opened 2023-03-24 01:01 UTC
Just wondering when a beta of 388.2 might drop?

**Comment by gnuton** [comment] 2023-03-24 09:03
Hi,
please wait for the merge to be completed. 
the merge will be complete once I merge everything in the gnuton-master.
Please note DSL-AC68U do not support 388 so you will need to use the 386 branch.
I have not merged the 386 yet since I am still waiting for the  GPLs frmo ASUS

**Comment by gnuton** [comment] 2023-03-24 09:06
388.2 stable won't happen before may.

**Comment by gnuton** [comment] 2023-03-27 07:14
Closing this as duplicate of https://github.com/gnuton/asuswrt-merlin.ng/issues/365
For all questions relatedto this topic please the issue above

**Closed by gnuton** 2023-03-27 07:14 UTC
Labels: enhancement
