### ISSUE TITLE
Error when uploading firmware 386.08_0-gnuton1 to RT-AX92U (half solved)

### ISSUE THREAD

**Issue by vdbseb1983** [gnuton/asuswrt-merlin.ng#270] opened 2022-10-29 18:17 UTC
**Router Model Affected**
RT-AX92

**Firmware Version Affected**
386.08_0-gnuton1

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
Error message when uploading firmware
Then goes back to recovery/safe image

**To Reproduce**
Click on manual upgrade file =>> Loading

**Expected behavior**
Expect to get file correct to update 

**Screenshots**
![Capture d’écran 2022-10-29 à 19 57 03](https://user-images.githubusercontent.com/71528002/198846656-2d30b4fe-c3eb-432a-8ef7-7c5c26f41c17.png)

Other info:
![Screenshot 2022-10-29 at 20-12-56 ASUS Wireless Router RT-AX92U - Mise à jour du firmware](https://user-images.githubusercontent.com/71528002/198846775-09e7cd52-9215-48c0-8a13-8a7cb06ef867.png)

Dump:
[Dump RT AX 92U.pdf](https://github.com/gnuton/asuswrt-merlin.ng/files/9894322/Dump.RT.AX.92U.pdf)

**Comment by vdbseb1983** [comment] 2022-10-29 19:06
Half solved: made error continue, as soon as returned directly to GUI: direct upload of image ok (du to less than 32mb), seems to check size of the "w" (ubi) image !

**Comment by gnuton** [comment] 2022-12-27 08:20
I will close this bug since it works. please re-openit if it still happens. I cannot reproduce this

**Closed by gnuton** 2022-12-27 08:20 UTC
Labels: bug
