### ISSUE TITLE
Guest network can't access internet if 'Access Intranet' is disabled

### ISSUE THREAD

**Issue by osmanelitok** [gnuton/asuswrt-merlin.ng#74] opened 2021-01-30 00:18 UTC
**Firmware Version Affected **

386.00_0-gnuton0_alpha9

**Is this bug present in upstream Merlin releases too?**
Yes

**Describe the bug**

1. also does not work without open intranet. There is no "Sync to AiMesh Node" option in the 2nd and 3rd. It may be due to this. "Bandwidth Limiter" does not work on devices other than the main modem.

When the "Sync to AiMesh Node" option is turned on in the guest network, the guest connected from aimesh devices other than the main modem connects without speed. "Bandwidth Limiter" does not work on devices other than the main modem. When the guest is given 10/1 mb speed, the main modem is also useful, but it connects at 50 / 7mb from the other aimesh device.

**Expected behavior**

Allow Guests to access the Internet when Intranet Access is disabled.

When "Sync to AiMesh Node" is active, let "Bandwidth Limiter" run.

**Screenshots**

![1](https://user-images.githubusercontent.com/65765917/106339830-cee3de80-62a8-11eb-835c-b68032d7ee11.PNG)
![2](https://user-images.githubusercontent.com/65765917/106339839-d60aec80-62a8-11eb-99e4-beb200744f4d.PNG)

**Comment by gnuton** [comment] 2021-02-04 14:34
Duplicate of https://github.com/gnuton/asuswrt-merlin.ng/issues/56

**Closed by gnuton** 2021-02-04 14:34 UTC
Labels: bug

**Comment by osmanelitok** [comment] 2021-02-05 03:48
not a copy. I've seen 56 years but there are more problems here.

**Comment by gnuton** [comment] 2021-02-05 14:02
Tested this with my AIMesh setup and everything works
Master node was a DSL-AX82U btw, but the code is the same as for the DSL-AC68U. The only difference is in some prebuilds

Internet works even if Access interent is enabled or disabled.
![image](https://user-images.githubusercontent.com/576580/107043191-f2d08400-67c2-11eb-8b87-0c8d69a2b48e.png)

Bandwith is correctly limited to limits set in the configuration
![image](https://user-images.githubusercontent.com/576580/107043225-011ea000-67c3-11eb-955a-ad788c38775b.png)

**Comment by osmanelitok** [comment] 2021-02-05 20:08
yes aimesh works on main modem while connected. however, the speed limiter does not work on other modems. Also, I couldn't even connect to the network with the intranet turned off and I had to open the intranet to connect. :)

**Comment by gnuton** [comment] 2021-02-06 00:34
Can you tell me more about your setup? Are you using dsl ac68u as master
node ? What kind of modem are you using as ai mesh slave?

**Comment by osmanelitok** [comment] 2021-02-06 00:56
yes, main modem dsl-ac68u and 2 rt-ac68u connected to it.

**Comment by gnuton** [comment] 2021-02-06 21:21
Confirmed as working from @Zendilar
 https://www.snbforums.com/threads/dsl-ac68u-asuswrt-merlin-386-x-alphas-for-dsl-ac68u-are-now-available.68295/page-4#post-660642
