### ISSUE TITLE
Netwok Map 0 Clients

### ISSUE THREAD

**Issue by micron888** [gnuton/asuswrt-merlin.ng#436] opened 2023-07-22 02:21 UTC
Models:TUF-AX5400 v1

**Firmware Version Affected**
[Unstable: 388.4_0-gnuton0_alpha1]

**Is this bug present in upstream Merlin releases too?**
388.2_2 is ok

**Describe the bug**
network map showing 0 devices

**Comment by Roki100** [comment] 2023-07-22 18:18
same on RT-AX82U, also running 388.4_0-gnuton0_alpha1]

**Comment by micron888** [comment] 2023-09-12 22:55
Gnuton,
Do you mind sharing the image :)

**Comment by gnuton** [comment] 2023-09-13 19:06
https://app.circleci.com/pipelines/github/gnuton/asuswrt-merlin.ng/1592/workflows/ddd141b0-01ed-496c-8b45-b7a6b4835fce
click the model then "artifact"

**Comment by Roki100** [comment] 2023-09-13 20:37
can confirm the issue is gone on latest build linked above

**Comment by micron888** [comment] 2023-09-13 23:08
latest build resolve network client map issue.
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/59114523/e9c45646-12a2-46e0-9d17-98ed8918062f)

**Comment by micron888** [comment] 2023-09-14 23:15
Web login outside wifi not working.
Log show connection closed unexpectedly

**Comment by gnuton** [comment] 2023-09-15 16:44
Could you please open a new ticket for different issues? Otherwise they are
hard to be tracked

**Comment by gnuton** [comment] 2023-09-23 07:07
closing this since fixed

**Closed by gnuton** 2023-09-23 07:07 UTC
Labels: bug, alpha, critical-issue, 388_4
