### ISSUE TITLE
Game and Open NAT options (port opening, QOS) none work. 

### ISSUE THREAD

**Issue by osmanelitok** [gnuton/asuswrt-merlin.ng#75] opened 2021-01-30 00:23 UTC
**Firmware Version Affected **

386.00_0-gnuton0_alpha9

**Is this bug present in upstream Merlin releases too?**

No

**Describe the bug**

Game and Open NAT options (port opening, QOS) none work. I tried it for CS GO.
When I make all the settings and say save, it does not save.

**Comment by gnuton** [comment] 2021-02-06 21:19
I have not tested this yet but works for @Zendilar
https://www.snbforums.com/threads/dsl-ac68u-asuswrt-merlin-386-x-alphas-for-dsl-ac68u-are-now-available.68295/page-4#post-660642

**Comment by gnuton** [comment] 2021-02-07 09:07
I jus tested this and I do see the new game added.
![image](https://user-images.githubusercontent.com/576580/107141949-27138400-692c-11eb-8140-07c7f4c3e518.png)
Can you please elaborate more on what are you doing?

**Comment by zendilar** [comment] 2021-02-07 09:30
Have you hit Apply, 
When you add a game or you set a port manually the gui saws it as added, but after you press apply nothing appears in the list.
Also I see that your port forwarding switch is set to disable try putting it to enable check
Zendilar
 

    Στις Κυριακή, 7 Φεβρουαρίου 2021, 11:07:33 π.μ. EET, ο χρήστης Antonio Aloisio <notifications@github.com> έγραψε:  
 
 


I jus tested this and I do see the new game added.

Can you please elaborate more on what are you doing?

**Comment by gnuton** [comment] 2021-02-17 00:43
@osmanelitok we cannot reproduce this. I will close it.

**Closed by gnuton** 2021-02-17 00:43 UTC
Labels: bug
