### ISSUE TITLE
Administration > System - 'Apply' button not working (TUF-AX5400 | 388.4_0-gnuton0_alpha1)

### ISSUE THREAD

**Issue by cristobalo7** [gnuton/asuswrt-merlin.ng#444] opened 2023-08-06 09:50 UTC
**Router Model Affected**
TUF-AX5400

**Firmware Version Affected**
388.4_0-gnuton0_alpha1

(TUF-AX5400_388.4_0-gnuton0_alpha1_puresqubi.w)

**Is this bug present in upstream Merlin releases too?**
Unknown

**Describe the bug**
'Apply' button not working under 'Administration' > 'System' 

**To Reproduce**
1. 'Factory Reset' router
2. Scroll down to 'Administration'
3. Click on 'System' tab
4. Make any configuration/changes
5. Click on 'Apply'
6. No respond, button not working

**Expected behavior**
Configuration/changes saved when click on 'Apply'

Thank you.

**Comment by master88wi** [comment] 2023-08-28 20:29
+1

**Comment by gnuton** [comment] 2023-09-24 07:07
![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/576580/3b91807d-f65e-419e-a36c-6db4c4157f79)
The problem is a missing var pagecache_ratio.

**Comment by gnuton** [comment] 2023-09-24 07:21
This should fix the issue 22d1f0eb933c842f6400aa4b06dde49923bdf7df
testing

**Comment by gnuton** [comment] 2023-09-24 23:22
https://output.circle-artifacts.com/output/job/31bc971b-58a1-46f5-b26e-580ba8600573/artifacts/0/workspace/release/TUF-AX5400_3004_388.4_0_puresqubi.w

here the image with the fix. the fix is now in the master line.
I will close this as fixed

**Closed by gnuton** 2023-09-24 23:22 UTC
Labels: bug, alpha, beta, 388_4
