### ISSUE TITLE
XT8 V1: Versions > RT-AX95Q_3004_388.5_0 cannot display AI Mesh nodes

### ISSUE THREAD

**Issue by colbsure** [gnuton/asuswrt-merlin.ng#592] opened 2024-05-18 10:57 UTC
**Router Model Affected**
Models: XT8 v1

**Firmware Version Affected**
3004.388.6_0 or newer

**Is this bug present in upstream Merlin releases too?**
Do not know.

**Describe the bug**
When installing version 6_0 or newer the AI Mesh page of the web interface is blank - looks like a javascript error is causing issues.

A fulll reset was tried with the broken version and did not help.

Problem is repeatable.  Merely upgrading causes the issue and downgrading solves it.  

Browser was Firefox but the issue is evident with Edge (a Chrome derivative).

**To Reproduce**
Upgrade firmware to 6_0, 6_2 or 7_1

**Expected behavior**
The AIMesh page shows as expected in the WebUI.

**Screenshots**
Version 6_0 is broken:
![6 broken](https://github.com/gnuton/asuswrt-merlin.ng/assets/2979029/0c3995a1-e45a-4c5c-9f50-321762491926)

Version 5_0 is fine with no javascript error.
![5 working](https://github.com/gnuton/asuswrt-merlin.ng/assets/2979029/9a38a43f-44c2-49fb-b368-da71dd86cbcf)

**Comment by ajayramaswamy** [comment] 2024-05-19 02:23
duplicate of #542

**Comment by gnuton** [comment] 2024-05-20 04:51
@ajayramaswamy is this something you have experienced too?
Do you get the same error in the JS console?

**Comment by gnuton** [comment] 2024-05-20 06:38
I just flashed the latest beta and the problem is not there.

![image](https://github.com/gnuton/asuswrt-merlin.ng/assets/576580/17bfee42-4988-470f-b3b0-37a4d892dace)

**Closed** 2024-05-20 12:14 UTC
Labels: bug

**Comment by gnuton** [comment] 2024-05-20 12:21
I missed it was in access point mode. This happens only in that case. 
Closing as duplicate of #542
