### ISSUE TITLE
2.4ghz WiFi is not showing rt-ax82u

### ISSUE THREAD

**Issue by shrek1802** [gnuton/asuswrt-merlin.ng#156] opened 2022-02-06 10:51 UTC
**Router Model Affected**
Models: RT-AX82U

**Firmware Version Affected**
386.04_0-gnuton2

**Describe the bug**
So when rebooting the router there is no WiFi at all if I disable the smart connect then re enable I get WiFi. I have a few devices that can only use 2.4ghz and no matter what I do these cannot see the WiFi.

Also if I separate the band's to 2.4 and 5.0 the 2.4 and rename one the 2.4 is not showing up on my phone when scanning for WiFi only the 5.0.

**Comment by gnuton** [comment] 2022-02-06 17:16
too weird.. do you still get this issue if you reset to factory settings?

**Comment by shrek1802** [comment] 2022-02-06 19:31
Yes first thing I did was reset to factory settings

**Comment by shrek1802** [comment] 2022-02-07 16:40
Anyone think of anything I can try ?

**Comment by gnuton** [comment] 2022-02-08 09:17
1. does the stock firmware have the same issue? or is this something you see only with Merlin?
2. can you see the WiFi from a new device? or the wifi is not visible to any of your clients?
3. have you tried to change any parameter in the http://router.asus.com/Advanced_WAdvanced_Content.asp ? some old wireless adapter may have issues with power management

**Comment by gnuton** [comment] 2022-02-08 22:17
BTW I have bee told that some users are experiencing WiFi issues with IOT devices iwth the current GPL release.
46065 GPL may fix this.
We are currently receiing this new GPL from ASsus. Eric has already started the merge.

**Comment by shrek1802** [comment] 2022-02-09 10:53
Yeah funny u say that it is IOT devices I'm having the problem with with they all have tasmota firmware on them. I will wait for the update and let u no.  I just did understand after rebooting why there was no WiFi.

**Comment by gnuton** [comment] 2022-02-09 11:00
the new firmware will hopefully be in beta or alpha by the end of Feb or
middle of next month.
In the meantime you may double check if the stock firmware works for you..
If you do so that will help me a lot to understand if the problem is
because of Asus or because I did something wrong elsewhere.. but as for now
I do not have way for testing and checking this.

**Comment by shrek1802** [comment] 2022-02-09 20:29
I will flash the stock firmware and report back mate

**Comment by vladut123** [comment] 2022-02-09 20:52
> BTW I have bee told that some users are experiencing WiFi issues with IOT devices iwth the current GPL release.
> 46065 GPL may fix this.
> We are currently receiing this new GPL from ASsus. Eric has already started the merge for some devices.

iwth or with?

**Comment by shrek1802** [comment] 2022-02-09 21:16
So flashed the lastest stock firmware over the custom one you make and both channels when separated can be see from my phone and with all my IOT devices.

But with a little more digging what I have found of u flick the switch enable smart connect back on you can't see any WiFi. If you then goto quick internet setup and tell that to run the networks joined all comes back on and you can see wifi with everything again. That all with stock firmware

**Comment by gnuton** [comment] 2022-02-10 15:15
@shrek1802 thanks for checking this. You tested the latest stock firmware which is 46061.
The new stable will be most likely be based on 46065. which is pretty much the same as 61... but I do not have the full changelog yet.

**Comment by shrek1802** [comment] 2022-02-12 02:32
Not a problem fingers crossed the new one fixes the problems I'm having

**Comment by shrek1802** [comment] 2022-03-02 01:52
@gnuton sent u a little something on PayPal mate keep up the good work and any ETA on the new version that I'm hoping fixes this error I was getting ?

**Comment by shrek1802** [comment] 2022-03-02 11:28
Nice mate thank you

**Comment by gnuton** [comment] 2022-03-26 12:43
@shrek1802 can i close issue? The new stable is out and the issues with IoT devices may have been resolved by the newest drivers

**Closed** 2022-03-28 08:58 UTC
Labels: bug
